config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "owner" => "static_pages#owner"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  def owner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t ".title" %></title>
    <%= stylesheet_link_tag "application", media: "all",
      "data-turbolinks-track": true %>
    <%= javascript_include_tag "application", "data-turbolinks-track": true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render "shared/navbar" unless current_page?(owner_path)%>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed"
        data-toggle="collapse" data-target="#navbar" aria-expanded="false"
        aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#"><%= t ".title" %></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse em-text">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#"><%= t ".home" %></a></li>
        <li><a href="#about"><%= t ".about" %></a></li>
        <li><a href="#contact"><%= t ".contact" %></a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/static_pages/home.html.erb
<section>
  <div class="jumbotron">
    <div class="container">
      <div class="col-md-6">
        <h1>Hello, world!</h1>
        <p>This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
      </div>
    </div>
  </div>
</section>

<section id = "feature">
  <div class= "container">
    <div class= "row">
      <div class= "col-md-4">
        <%= image_tag(image_url("/logo1.jpg"), size: "300x240",
          class: "img-square avatar avatar-original") %>
        <h2> Lorem ipsum dolor sit amet </h2>
        <p> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
          labore et dolore magna aliqua.</p>
        <a href="#" class="btn btn-default btn-feature" role="button"> Read More</a>
      </div>
      <div class= "col-md-4 demo">
        <%= image_tag(image_url("/logo2.jpg"), size: "300x240",
          class: "img-square avatar avatar-original") %>
        <h2> Lorem ipsum dolor sit amet </h2>
        <p> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
          labore et dolore magna aliqua.</p>
        <a href="#" class="btn btn-default btn-feature" role="button"> Read More</a>
      </div>
      <div class= "col-md-4 demo">
        <%= image_tag(image_url("/logo3.jpg"), size: "300x240",
          class: "img-square avatar avatar-original") %>
        <h2> Lorem ipsum dolor sit amet </h2>
        <p> Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
          labore et dolore magna aliqua.</p>
        <a href="#" class="btn btn-default btn-feature" role="button"> Read More</a>
      </div>
    </div>
  </div>
</section>

<section id="details">
  <div class= "container">
    <div class= "row">
      <div class= "col-md-5 col-md-offset-1">
        <h1> List of Features </h1>
        <ul>
          <li><i class= "glyphicon glyphicon-ok"></i> Sed ut perspiciatis unde omnis </li>
          <li><i class= "glyphicon glyphicon-ok"></i> Iste natus error sit voluptatem</li>
          <li><i class= "glyphicon glyphicon-ok"></i> Accusantium doloremque laudantium</li>
          <li><i class= "glyphicon glyphicon-ok"></i> Totam rem aperiam, eaque ipsa quae</li>
          <li><i class= "glyphicon glyphicon-ok"></i> Ab illo inventore veritatis</li>
          <li><i class= "glyphicon glyphicon-ok"></i> Architecto beatae vitae dicta</li>
        </ul>
      </div>
      <div class= "col-md-4 col-md-offset-1 logo">
        <%= image_tag(image_url("/clipart.jpg"), size: "350x350",
          class: "img-square avatar avatar-original") %>
      </div>
    </div>
  </div>
</section>
<footer>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-6 menu">
        <ul>
          <li> <a href= "#"> Home </a></li>
          <li> <a href= "#"> About</a></li>
          <li> <a href= "#"> Contact</a></li>
          <li> <a href= "#"> Privacy Policy</a></li>
          <li> <a href= "<%= owner_path %>"> Owner Information </a></li>
        </ul>
      </div>
      <div class= "col-md-6 copyright">
        <p>Copyright &copy; 2016. All Rights Reserved. By Dren Gravidez. </p>
      </div>
    </div>
  </div>
</footer>

app/views/static_pages/owner.html.erb
<section id="owner">
  <div class="container mainpage">
    <header>
      <%= image_tag(image_url("/profile-img.jpg"), size: "150x150",
        class: "img-circle owner-img") %>
      <h1> Hi! <br/>
        My name is <strong>Dren Gravidez</strong>
        and I am a Programmer
      </h1>
      <hr/>
    </header>
    <body>
      <div class="row">
        <div class="col-md-7">
          <h2># About Me </h2>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
        </div>
        <div class="col-md-5">
          <h2># Contact Info </h2>
          <ul class="contact-list">
            <li> <a href="#">
              <%= image_tag(image_url("/owner_page/phone.jpg"),
                class: "contact-img") %> (63)926 4520 190 </a>
            </li>
            <li> <a href="#">
              <%= image_tag(image_url("/owner_page/gmail.png"),
                class: "contact-img") %> gravides.dren@gmail </a>
            </li>
            <li> <a href="https://ph.linkedin.com/in/aldrin-gravides-3572a7101">
              <%= image_tag(image_url("/owner_page/linkedin.png"),
                class: "contact-img") %> Aldrin Gravides </a>
            </li>
            <li> <a href="https://facebook.com/drengravidez">
              <%= image_tag(image_url("/owner_page/fb.jpg"),
                class: "contact-img") %> Dren Gravidez </a>
            </li>
            <li> <a href="https://twitter.com/xaknidren">
              <%= image_tag(image_url("/owner_page/twitter.png"),
                class: "contact-img") %> @xaknidren </a>
            </li>
            <li> <a href="https://instagram.com/xaknidren">
              <%= image_tag(image_url("/owner_page/instagram.jpg"),
                class: "contact-img") %> @xaknidren </a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-7">
          <h2># Education and Experience</h2>
          <div class="media">
            <div class="media-left pull-left">
              <a href="#">
                2016-Pres
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">Framgia Philippines</h4>
              <p> Junior Web Developer </p>
            </div>
          </div>
          <div class="media">
            <div class="media-left pull-left">
              <a href="#">
                2013-2015
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">Information Managers Inc</h4>
              <p> Junior Programmer </p>
            </div>
          </div>
          <div class="media">
            <div class="media-left pull-left">
              <a href="#">
                2008-2013
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">University of the East, Manila</h4>
              <p> Bachelor of Scienece in Information Technology </p>
            </div>
          </div>
          <div class="media">
            <div class="media-left pull-left">
              <a href="#">
                2004-2008
              </a>
            </div>
            <div class="media-body">
              <h4 class="media-heading">OLRA College Foundation</h4>
              <p> High School</p>
            </div>
          </div>
        </div>
        <div class="col-md-5">
          <h2># Skills </h2>
          <div class="row skills">
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width:90%;">
                <p>Ruby on Rails</p>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width:90%;">
                <p>Progress OpenEdge</p>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width:100%;">
                <p>HTML / CSS</p>
              </div>
            </div>
            <div class="progress">
              <div class="progress-bar" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width:100%;">
                <p>MySQL</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-7">
          <h2># Services</h2>
            <div class="alert alert-success" role="alert"> <i class="glyphicon glyphicon-ok"></i> At vero eos et accusamus et iusto odio. </div>
            <div class="alert alert-info" role="alert"><i class="glyphicon glyphicon-ok"></i> Dignissimos ducimus qui blanditiis praesentium voluptatum. </div>
            <div class="alert alert-success" role="alert"> <i class="glyphicon glyphicon-ok"></i> Deleniti atque corrupti quos dolores et quas. </div>
            <div class="alert alert-info" role="alert"><i class="glyphicon glyphicon-ok"></i> Molestias excepturi sint occaecati cupiditate non provident. </div>
            <div class="alert alert-success" role="alert"> <i class="glyphicon glyphicon-ok"></i> Similique sunt in culpa qui officia deserunt mollitia animi. </div>
            <div class="alert alert-info" role="alert"><i class="glyphicon glyphicon-ok"></i> Id est laborum et dolorum fuga. Et harum quidem rerum facilis est. </div>
          </div>
          <div class="col-md-5">
            <h2># Projects</h2>
            <ul class="work-list">
              <li> <a href="#"> <%= image_tag(image_url("/recent_projs/work1.jpg"), size: "400x80",
                class: "work-img") %> </a> </li>
              <li> <a href="#"> <%= image_tag(image_url("/recent_projs/work2.png"), size: "400x80",
                class: "work-img") %> </a> </li>
              <li> <a href="#"> <%= image_tag(image_url("/recent_projs/work3.jpg"), size: "400x80",
                class: "work-img") %> </a> </li>
              <li> <a href="#"> <%= image_tag(image_url("/recent_projs/work4.jpg"), size: "400x80",
                class: "work-img") %> </a> </li>
              <li> <a href="#"> <%= image_tag(image_url("/recent_projs/work5.jpg"), size: "400x80",
                class: "work-img") %> </a> </li>
            </ul>
          </div>
        </div>
      </div>
    </body>
<footer>
  <div class= "container">
    <div class= "row">
      <div class= "col-md-6 menu">
        <ul>
          <li> <a href= "<%= root_path %>"> Home </a></li>
        </ul>
      </div>
      <div class= "col-md-6 copyright">
        <p>Copyright &copy; 2016. All Rights Reserved. By Dren Gravidez. </p>
      </div>
    </div>
  </div>
</footer>
  </div>
</section>